import { Product } from "@/types/product";
const shopData: Product[] = [
  {
    title: "Havit HV-G69 USB Gamepad",
    reviews: 15,
    price: 59.0,
    discountedPrice: 29.0,
    id: 1,
    externalUrl: "https://example.com/products/1",
    slug: "havit-hv-g69-usb-gamepad",
    currency: "$",
    categoryIds: ["1"],
    categoryNames: ["Games & Videos"],
    tags: ["gamepad", "usb"],
    colors: ["black", "red"],
    imgs: {
      thumbnails: ["/images/products/product-1-sm-1.png", "/images/products/product-1-sm-2.png"],
      previews: ["/images/products/product-1-bg-1.png", "/images/products/product-1-bg-2.png"],
    },
  },
  {
    title: "iPhone 14 Plus , 6/128GB",
    reviews: 5,
    price: 899.0,
    discountedPrice: 99.0,
    id: 2,
    externalUrl: "https://example.com/products/2",
    slug: "iphone-14-plus",
    currency: "$",
    categoryIds: ["3"],
    categoryNames: ["Mobile & Tablets"],
    tags: ["iphone", "apple"],
    colors: ["blue", "purple"],
    imgs: {
      thumbnails: ["/images/products/product-2-sm-1.png", "/images/products/product-2-sm-2.png"],
      previews: ["/images/products/product-2-bg-1.png", "/images/products/product-2-bg-2.png"],
    },
  },
  {
    title: "Apple iMac M1 24-inch 2021",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    id: 3,
    externalUrl: "https://example.com/products/3",
    slug: "apple-imac-m1",
    currency: "$",
    categoryIds: ["2"],
    categoryNames: ["Laptop & PC"],
    tags: ["imac", "apple"],
    colors: ["silver", "blue"],
    imgs: {
      thumbnails: ["/images/products/product-3-sm-1.png", "/images/products/product-3-sm-2.png"],
      previews: ["/images/products/product-3-bg-1.png", "/images/products/product-3-bg-2.png"],
    },
  },
  {
    title: "MacBook Air M1 chip, 8/256GB",
    reviews: 6,
    price: 59.0,
    discountedPrice: 29.0,
    id: 4,
    externalUrl: "https://example.com/products/4",
    slug: "macbook-air-m1",
    currency: "$",
    categoryIds: ["2"],
    categoryNames: ["Laptop & PC"],
    tags: ["macbook", "apple"],
    colors: ["gold", "silver"],
    imgs: {
      thumbnails: ["/images/products/product-4-sm-1.png", "/images/products/product-4-sm-2.png"],
      previews: ["/images/products/product-4-bg-1.png", "/images/products/product-4-bg-2.png"],
    },
  },
  {
    title: "Apple Watch Ultra",
    reviews: 3,
    price: 99.0,
    discountedPrice: 29.0,
    id: 5,
    externalUrl: "https://example.com/products/5",
    slug: "apple-watch-ultra",
    currency: "$",
    categoryIds: ["7"],
    categoryNames: ["Watches"],
    tags: ["watch", "apple"],
    colors: ["orange", "black"],
    imgs: {
      thumbnails: ["/images/products/product-5-sm-1.png", "/images/products/product-5-sm-2.png"],
      previews: ["/images/products/product-5-bg-1.png", "/images/products/product-5-bg-2.png"],
    },
  },
  {
    title: "Logitech MX Master 3 Mouse",
    reviews: 15,
    price: 59.0,
    discountedPrice: 29.0,
    id: 6,
    externalUrl: "https://example.com/products/6",
    slug: "logitech-mx-master-3",
    currency: "$",
    categoryIds: ["2"],
    categoryNames: ["Laptop & PC"],
    tags: ["mouse", "logitech"],
    colors: ["black", "gray"],
    imgs: {
      thumbnails: ["/images/products/product-6-sm-1.png", "/images/products/product-6-sm-2.png"],
      previews: ["/images/products/product-6-bg-1.png", "/images/products/product-6-bg-2.png"],
    },
  },
  {
    title: "Apple iPad Air 5th Gen - 64GB",
    reviews: 15,
    price: 59.0,
    discountedPrice: 29.0,
    id: 7,
    externalUrl: "https://example.com/products/7",
    slug: "apple-ipad-air-5",
    currency: "$",
    categoryIds: ["3"],
    categoryNames: ["Mobile & Tablets"],
    tags: ["ipad", "apple"],
    colors: ["blue", "pink"],
    imgs: {
      thumbnails: ["/images/products/product-7-sm-1.png", "/images/products/product-7-sm-2.png"],
      previews: ["/images/products/product-7-bg-1.png", "/images/products/product-7-bg-2.png"],
    },
  },
  {
    title: "Asus RT Dual Band Router",
    reviews: 15,
    price: 59.0,
    discountedPrice: 29.0,
    id: 8,
    externalUrl: "https://example.com/products/8",
    slug: "asus-router",
    currency: "$",
    categoryIds: ["2"],
    categoryNames: ["Laptop & PC"],
    tags: ["router", "asus"],
    colors: ["black"],
    imgs: {
      thumbnails: ["/images/products/product-8-sm-1.png", "/images/products/product-8-sm-2.png"],
      previews: ["/images/products/product-8-bg-1.png", "/images/products/product-8-bg-2.png"],
    },
  },
];

export default shopData;
